// Maps each era id to its background image asset.
// Generated by scripts/generate-app-images.ts.
import { EraId } from '../../data/eras';

export const eraBackgrounds: Record<EraId, number | undefined> = {
  ancient:        require('../../../assets/era-backgrounds/ancient.webp'),
  'dark-ages':    require('../../../assets/era-backgrounds/dark-ages.webp'),
  medieval:       require('../../../assets/era-backgrounds/medieval.webp'),
  'early-modern': require('../../../assets/era-backgrounds/early-modern.webp'),
  napoleonic:    require('../../../assets/era-backgrounds/napoleonic.webp'),
  industrial:     require('../../../assets/era-backgrounds/industrial.webp'),
  'world-wars':   require('../../../assets/era-backgrounds/world-wars.webp'),
  modern:         require('../../../assets/era-backgrounds/modern.webp'),
};
