import * as fs from 'fs';
import * as path from 'path';

const ASSETS_DIR = path.join(__dirname, '..', 'assets', 'battles');
const OUT = path.join(__dirname, '..', 'src', 'data', 'battleImages.ts');

const files = fs.readdirSync(ASSETS_DIR)
  .filter(f => /^battle-\d+\.webp$/.test(f))
  .sort((a, b) => {
    const na = Number(a.match(/\d+/)![0]);
    const nb = Number(b.match(/\d+/)![0]);
    return na - nb;
  });

if (files.length === 0) {
  console.error(`No battle-N.webp files found in ${ASSETS_DIR}`);
  process.exit(1);
}

const lines: string[] = [];
lines.push('// AUTO-GENERATED by scripts/generate-battle-images.ts — do not edit by hand.');
lines.push('// Run: npm run gen:images');
lines.push('');
lines.push('export const battleImages: Record<number, number> = {');
for (const f of files) {
  const id = Number(f.match(/\d+/)![0]);
  lines.push(`  ${id}: require('../../assets/battles/${f}'),`);
}
lines.push('};');
lines.push('');
lines.push('export function getBattleImage(id: number): number | undefined {');
lines.push('  return battleImages[id];');
lines.push('}');
lines.push('');

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${OUT} with ${files.length} entries.`);
